### ISSUE TITLE
Idea - Instructions for students to view live app as they edit the code

### ISSUE THREAD

**Issue by juliamuiruri4** [microsoft/codespaces-project-template-js#10]
Since the students would need to manually run `npm run start`, perhaps it's a nice add to mention the steps to take whenever they would like to see their changes on the live site?

Update on this instruction on the readme:
![image](https://user-images.githubusercontent.com/40116776/194075153-7b4b3816-b0ee-4d99-afe6-83d36bb6c0dc.png)

**Comment by saragibby** [comment]
Thanks @juliamuiruri4 for pointing this out! I updated the readme to inlude a step to run `npm start` manually after the install. Including the prompt that the app has started.
